name: Generate Preview Deployment
on:
  pull_request:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_SECRET_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_SECRET_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel-cli-deploy
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_SECRET_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --confirm)
          echo "PREVIEW_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Comment on PR with Preview URL
        uses: phulsechinmay/rewritable-pr-comment@v0.3.0
        with:
          message: |
            This pull request has been deployed to Vercel.
            <table>
              <tr>
                <td><strong>✅ Preview:</strong></td>
                <td><a href='${{ env.PREVIEW_URL }}'>${{ env.PREVIEW_URL }}</a></td>
              </tr>
            </table>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: "vercel-deploy"
